### ISSUE TITLE
To use or not to use Type suffix on protocols

### ISSUE THREAD

**Issue by paulofaria** [swift-x/s4#3]
It seems swift is removing the `Type` suffix from their protocols. Should we use them or follow the guidelines and not?

Reference: https://swift.org/documentation/api-design-guidelines/
> Protocols that describe what something is should read as nouns (e.g. Collection).

e.g. 
`StreamType` vs `Stream`

**Comment by tannernelson** [comment]
Definitely no type. The Swift API Design Guidelines are clear.

**Comment by paulofaria** [comment]
I'm down! :rocket: ?
